--
-- MAKE SURE WE ARE MAKING CHANGES TO THE SYSTEM SCHEMA
--

SET search_path TO system;


--
-- CREATE countries TABLE
--

CREATE TABLE countries
(
	code 			CHAR(3) PRIMARY KEY NOT NULL,
	alpha_2_code 		CHAR(2) NOT NULL,
	name 			VARCHAR NOT NULL,
	nationality 		VARCHAR NOT NULL
);

INSERT INTO countries (code, alpha_2_code, name, nationality) VALUES
('AFG', 'AF', 'Afghanistan', 'Afghan'),
('ALA', 'AX', 'Åland Islands', 'Åland Island'),
('ALB', 'AL', 'Albania', 'Albanian'),
('DZA', 'DZ', 'Algeria', 'Algerian'),
('ASM', 'AS', 'American Samoa', 'American Samoan'),
('AND', 'AD', 'Andorra', 'Andorran'),
('AGO', 'AO', 'Angola', 'Angolan'),
('AIA', 'AI', 'Anguilla', 'Anguillan'),
('ATA', 'AQ', 'Antarctica', 'Antarctic'),
('ATG', 'AG', 'Antigua and Barbuda', 'Antiguan or Barbudan'),
('ARG', 'AR', 'Argentina', 'Argentine'),
('ARM', 'AM', 'Armenia', 'Armenian'),
('ABW', 'AW', 'Aruba', 'Aruban'),
('AUS', 'AU', 'Australia', 'Australian'),
('AUT', 'AT', 'Austria', 'Austrian'),
('AZE', 'AZ', 'Azerbaijan', 'Azerbaijani, Azeri'),
('BHS', 'BS', 'Bahamas', 'Bahamian'),
('BHR', 'BH', 'Bahrain', 'Bahraini'),
('BGD', 'BD', 'Bangladesh', 'Bangladeshi'),
('BRB', 'BB', 'Barbados', 'Barbadian'),
('BLR', 'BY', 'Belarus', 'Belarusian'),
('BEL', 'BE', 'Belgium', 'Belgian'),
('BLZ', 'BZ', 'Belize', 'Belizean'),
('BEN', 'BJ', 'Benin', 'Beninese, Beninois'),
('BMU', 'BM', 'Bermuda', 'Bermudian, Bermudan'),
('BTN', 'BT', 'Bhutan', 'Bhutanese'),
('BOL', 'BO', 'Bolivia (Plurinational State of)', 'Bolivian'),
('BES', 'BQ', 'Bonaire, Sint Eustatius and Saba', 'Bonaire'),
('BIH', 'BA', 'Bosnia and Herzegovina', 'Bosnian or Herzegovinian'),
('BWA', 'BW', 'Botswana', 'Motswana, Botswanan'),
('BVT', 'BV', 'Bouvet Island', 'Bouvet Island'),
('BRA', 'BR', 'Brazil', 'Brazilian'),
('IOT', 'IO', 'British Indian Ocean Territory', 'BIOT'),
('BRN', 'BN', 'Brunei Darussalam', 'Bruneian'),
('BGR', 'BG', 'Bulgaria', 'Bulgarian'),
('BFA', 'BF', 'Burkina Faso', 'Burkinabé'),
('BDI', 'BI', 'Burundi', 'Burundian'),
('CPV', 'CV', 'Cabo Verde', 'Cabo Verdean'),
('KHM', 'KH', 'Cambodia', 'Cambodian'),
('CMR', 'CM', 'Cameroon', 'Cameroonian'),
('CAN', 'CA', 'Canada', 'Canadian'),
('CYM', 'KY', 'Cayman Islands', 'Caymanian'),
('CAF', 'CF', 'Central African Republic', 'Central African'),
('TCD', 'TD', 'Chad', 'Chadian'),
('CHL', 'CL', 'Chile', 'Chilean'),
('CHN', 'CN', 'China', 'Chinese'),
('CXR', 'CX', 'Christmas Island', 'Christmas Island'),
('CCK', 'CC', 'Cocos (Keeling) Islands', 'Cocos Island'),
('COL', 'CO', 'Colombia', 'Colombian'),
('COM', 'KM', 'Comoros', 'Comoran, Comorian'),
('COD', 'CD', 'Congo (Democratic Republic of the)', 'Congolese (DRC)'),
('COG', 'CG', 'Congo (Republic of the)', 'Congolese (ROC)'),
('COK', 'CK', 'Cook Islands', 'Cook Island'),
('CRI', 'CR', 'Costa Rica', 'Costa Rican'),
('CIV', 'CI', 'Côte d''Ivoire', 'Ivorian'),
('HRV', 'HR', 'Croatia', 'Croatian'),
('CUB', 'CU', 'Cuba', 'Cuban'),
('CUW', 'CW', 'Curaçao', 'Curaçaoan'),
('CYP', 'CY', 'Cyprus', 'Cypriot'),
('CZE', 'CZ', 'Czech Republic', 'Czech'),
('DNK', 'DK', 'Denmark', 'Danish'),
('DJI', 'DJ', 'Djibouti', 'Djiboutian'),
('DMA', 'DM', 'Dominica', 'Dominican (Dominica)'),
('DOM', 'DO', 'Dominican Republic', 'Dominican (Dominican Republic)'),
('ECU', 'EC', 'Ecuador', 'Ecuadorian'),
('EGY', 'EG', 'Egypt', 'Egyptian'),
('SLV', 'SV', 'El Salvador', 'Salvadoran'),
('GNQ', 'GQ', 'Equatorial Guinea', 'Equatorial Guinean, Equatoguinean'),
('ERI', 'ER', 'Eritrea', 'Eritrean'),
('EST', 'EE', 'Estonia', 'Estonian'),
('ETH', 'ET', 'Ethiopia', 'Ethiopian'),
('FLK', 'FK', 'Falkland Islands (Malvinas)', 'Falkland Island'),
('FRO', 'FO', 'Faroe Islands', 'Faroese'),
('FJI', 'FJ', 'Fiji', 'Fijian'),
('FIN', 'FI', 'Finland', 'Finnish'),
('FRA', 'FR', 'France', 'French'),
('GUF', 'GF', 'French Guiana', 'French Guianese'),
('PYF', 'PF', 'French Polynesia', 'French Polynesian'),
('ATF', 'TF', 'French Southern Territories', 'French Southern Territories'),
('GAB', 'GA', 'Gabon', 'Gabonese'),
('GMB', 'GM', 'Gambia', 'Gambian'),
('GEO', 'GE', 'Georgia', 'Georgian'),
('DEU', 'DE', 'Germany', 'German'),
('GHA', 'GH', 'Ghana', 'Ghanaian'),
('GIB', 'GI', 'Gibraltar', 'Gibraltar'),
('GRC', 'GR', 'Greece', 'Greek, Hellenic'),
('GRL', 'GL', 'Greenland', 'Greenlandic'),
('GRD', 'GD', 'Grenada', 'Grenadian'),
('GLP', 'GP', 'Guadeloupe', 'Guadeloupe'),
('GUM', 'GU', 'Guam', 'Guamanian, Guambat'),
('GTM', 'GT', 'Guatemala', 'Guatemalan'),
('GGY', 'GG', 'Guernsey', 'Channel Island (Guernsey)'),
('GIN', 'GN', 'Guinea', 'Guinean'),
('GNB', 'GW', 'Guinea-Bissau', 'Bissau-Guinean'),
('GUY', 'GY', 'Guyana', 'Guyanese'),
('HTI', 'HT', 'Haiti', 'Haitian'),
('HMD', 'HM', 'Heard Island and McDonald Islands', 'Heard Island or McDonald Islands'),
('HND', 'HN', 'Honduras', 'Honduran'),
('HKG', 'HK', 'Hong Kong', 'Hong Kong, Hong Kongese'),
('HUN', 'HU', 'Hungary', 'Hungarian, Magyar'),
('ISL', 'IS', 'Iceland', 'Icelandic'),
('IND', 'IN', 'India', 'Indian'),
('IDN', 'ID', 'Indonesia', 'Indonesian'),
('IRN', 'IR', 'Iran', 'Iranian, Persian'),
('IRQ', 'IQ', 'Iraq', 'Iraqi'),
('IRL', 'IE', 'Ireland', 'Irish'),
('IMN', 'IM', 'Isle of Man', 'Manx'),
('ISR', 'IL', 'Israel', 'Israeli'),
('ITA', 'IT', 'Italy', 'Italian'),
('JAM', 'JM', 'Jamaica', 'Jamaican'),
('JPN', 'JP', 'Japan', 'Japanese'),
('JEY', 'JE', 'Jersey', 'Channel Island (Jersey)'),
('JOR', 'JO', 'Jordan', 'Jordanian'),
('KAZ', 'KZ', 'Kazakhstan', 'Kazakhstani, Kazakh'),
('KEN', 'KE', 'Kenya', 'Kenyan'),
('KIR', 'KI', 'Kiribati', 'I-Kiribati'),
('PRK', 'KP', 'Korea (Democratic People''s Republic of)', 'North Korean'),
('KOR', 'KR', 'Korea (Republic of)', 'South Korean'),
('KWT', 'KW', 'Kuwait', 'Kuwaiti'),
('KGZ', 'KG', 'Kyrgyzstan', 'Kyrgyzstani, Kyrgyz, Kirgiz, Kirghiz'),
('LAO', 'LA', 'Lao People''s Democratic Republic', 'Lao, Laotian'),
('LVA', 'LV', 'Latvia', 'Latvian'),
('LBN', 'LB', 'Lebanon', 'Lebanese'),
('LSO', 'LS', 'Lesotho', 'Basotho'),
('LBR', 'LR', 'Liberia', 'Liberian'),
('LBY', 'LY', 'Libya', 'Libyan'),
('LIE', 'LI', 'Liechtenstein', 'Liechtenstein'),
('LTU', 'LT', 'Lithuania', 'Lithuanian'),
('LUX', 'LU', 'Luxembourg', 'Luxembourg, Luxembourgish'),
('MAC', 'MO', 'Macao', 'Macanese, Chinese'),
('MKD', 'MK', 'Macedonia (the former Yugoslav Republic of)', 'Macedonian'),
('MDG', 'MG', 'Madagascar', 'Malagasy'),
('MWI', 'MW', 'Malawi', 'Malawian'),
('MYS', 'MY', 'Malaysia', 'Malaysian'),
('MDV', 'MV', 'Maldives', 'Maldivian'),
('MLI', 'ML', 'Mali', 'Malian, Malinese'),
('MLT', 'MT', 'Malta', 'Maltese'),
('MHL', 'MH', 'Marshall Islands', 'Marshallese'),
('MTQ', 'MQ', 'Martinique', 'Martiniquais, Martinican'),
('MRT', 'MR', 'Mauritania', 'Mauritanian'),
('MUS', 'MU', 'Mauritius', 'Mauritian'),
('MYT', 'YT', 'Mayotte', 'Mahoran'),
('MEX', 'MX', 'Mexico', 'Mexican'),
('FSM', 'FM', 'Micronesia (Federated States of)', 'Micronesian'),
('MDA', 'MD', 'Moldova (Republic of)', 'Moldovan'),
('MCO', 'MC', 'Monaco', 'Monégasque, Monacan'),
('MNG', 'MN', 'Mongolia', 'Mongolian'),
('MNE', 'ME', 'Montenegro', 'Montenegrin'),
('MSR', 'MS', 'Montserrat', 'Montserratian'),
('MAR', 'MA', 'Morocco', 'Moroccan'),
('MOZ', 'MZ', 'Mozambique', 'Mozambican'),
('MMR', 'MM', 'Myanmar', 'Burmese'),
('NAM', 'NA', 'Namibia', 'Namibian'),
('NRU', 'NR', 'Nauru', 'Nauruan'),
('NPL', 'NP', 'Nepal', 'Nepali, Nepalese'),
('NLD', 'NL', 'Netherlands', 'Dutch, Netherlandic'),
('NCL', 'NC', 'New Caledonia', 'New Caledonian'),
('NZL', 'NZ', 'New Zealand', 'New Zealand, NZ'),
('NIC', 'NI', 'Nicaragua', 'Nicaraguan'),
('NER', 'NE', 'Niger', 'Nigerien'),
('NGA', 'NG', 'Nigeria', 'Nigerian'),
('NIU', 'NU', 'Niue', 'Niuean'),
('NFK', 'NF', 'Norfolk Island', 'Norfolk Island'),
('MNP', 'MP', 'Northern Mariana Islands', 'Northern Marianan'),
('NOR', 'NO', 'Norway', 'Norwegian'),
('OMN', 'OM', 'Oman', 'Omani'),
('PAK', 'PK', 'Pakistan', 'Pakistani'),
('PLW', 'PW', 'Palau', 'Palauan'),
('PSE', 'PS', 'Palestine, State of', 'Palestinian'),
('PAN', 'PA', 'Panama', 'Panamanian'),
('PNG', 'PG', 'Papua New Guinea', 'Papua New Guinean, Papuan'),
('PRY', 'PY', 'Paraguay', 'Paraguayan'),
('PER', 'PE', 'Peru', 'Peruvian'),
('PHL', 'PH', 'Philippines', 'Philippine, Filipino'),
('PCN', 'PN', 'Pitcairn', 'Pitcairn Island'),
('POL', 'PL', 'Poland', 'Polish'),
('PRT', 'PT', 'Portugal', 'Portuguese'),
('PRI', 'PR', 'Puerto Rico', 'Puerto Rican'),
('QAT', 'QA', 'Qatar', 'Qatari'),
('REU', 'RE', 'Réunion', 'Réunionese, Réunionnais'),
('ROU', 'RO', 'Romania', 'Romanian'),
('RUS', 'RU', 'Russian Federation', 'Russian'),
('RWA', 'RW', 'Rwanda', 'Rwandan'),
('BLM', 'BL', 'Saint Barthélemy', 'Barthélemois'),
('SHN', 'SH', 'Saint Helena, Ascension and Tristan da Cunha', 'Saint Helenian'),
('KNA', 'KN', 'Saint Kitts and Nevis', 'Kittitian or Nevisian'),
('LCA', 'LC', 'Saint Lucia', 'Saint Lucian'),
('MAF', 'MF', 'Saint Martin (French part)', 'Saint-Martinoise'),
('SPM', 'PM', 'Saint Pierre and Miquelon', 'Saint-Pierrais or Miquelonnais'),
('VCT', 'VC', 'Saint Vincent and the Grenadines', 'Saint Vincentian, Vincentian'),
('WSM', 'WS', 'Samoa', 'Samoan'),
('SMR', 'SM', 'San Marino', 'Sammarinese'),
('STP', 'ST', 'Sao Tome and Principe', 'São Toméan'),
('SAU', 'SA', 'Saudi Arabia', 'Saudi, Saudi Arabian'),
('SEN', 'SN', 'Senegal', 'Senegalese'),
('SRB', 'RS', 'Serbia', 'Serbian'),
('SYC', 'SC', 'Seychelles', 'Seychellois'),
('SLE', 'SL', 'Sierra Leone', 'Sierra Leonean'),
('SGP', 'SG', 'Singapore', 'Singaporean'),
('SXM', 'SX', 'Sint Maarten (Dutch part)', 'Sint Maarten'),
('SVK', 'SK', 'Slovakia', 'Slovak'),
('SVN', 'SI', 'Slovenia', 'Slovenian, Slovene'),
('SLB', 'SB', 'Solomon Islands', 'Solomon Island'),
('SOM', 'SO', 'Somalia', 'Somali, Somalian'),
('ZAF', 'ZA', 'South Africa', 'South African'),
('SGS', 'GS', 'South Georgia and the South Sandwich Islands', 'South Georgia or South Sandwich Islands'),
('SSD', 'SS', 'South Sudan', 'South Sudanese'),
('ESP', 'ES', 'Spain', 'Spanish'),
('LKA', 'LK', 'Sri Lanka', 'Sri Lankan'),
('SDN', 'SD', 'Sudan', 'Sudanese'),
('SUR', 'SR', 'Suriname', 'Surinamese'),
('SJM', 'SJ', 'Svalbard and Jan Mayen', 'Svalbard'),
('SWZ', 'SZ', 'Swaziland', 'Swazi'),
('SWE', 'SE', 'Sweden', 'Swedish'),
('CHE', 'CH', 'Switzerland', 'Swiss'),
('SYR', 'SY', 'Syrian Arab Republic', 'Syrian'),
('TWN', 'TW', 'Taiwan, Province of China', 'Chinese, Taiwanese'),
('TJK', 'TJ', 'Tajikistan', 'Tajikistani'),
('TZA', 'TZ', 'Tanzania, United Republic of', 'Tanzanian'),
('THA', 'TH', 'Thailand', 'Thai'),
('TLS', 'TL', 'Timor-Leste', 'Timorese'),
('TGO', 'TG', 'Togo', 'Togolese'),
('TKL', 'TK', 'Tokelau', 'Tokelauan'),
('TON', 'TO', 'Tonga', 'Tongan'),
('TTO', 'TT', 'Trinidad and Tobago', 'Trinidadian or Tobagonian'),
('TUN', 'TN', 'Tunisia', 'Tunisian'),
('TUR', 'TR', 'Turkey', 'Turkish'),
('TKM', 'TM', 'Turkmenistan', 'Turkmen'),
('TCA', 'TC', 'Turks and Caicos Islands', 'Turks and Caicos Island'),
('TUV', 'TV', 'Tuvalu', 'Tuvaluan'),
('UGA', 'UG', 'Uganda', 'Ugandan'),
('UKR', 'UA', 'Ukraine', 'Ukrainian'),
('ARE', 'AE', 'United Arab Emirates', 'Emirati, Emirian, Emiri'),
('GBR', 'GB', 'United Kingdom of Great Britain and Northern Ireland', 'British, UK'),
('UMI', 'UM', 'United States Minor Outlying Islands', 'American (Minor Outlying Islands)'),
('USA', 'US', 'United States of America', 'American'),
('URY', 'UY', 'Uruguay', 'Uruguayan'),
('UZB', 'UZ', 'Uzbekistan', 'Uzbekistani, Uzbek'),
('VUT', 'VU', 'Vanuatu', 'Ni-Vanuatu, Vanuatuan'),
('VAT', 'VA', 'Vatican City State', 'Vatican'),
('VEN', 'VE', 'Venezuela (Bolivarian Republic of)', 'Venezuelan'),
('VNM', 'VN', 'Vietnam', 'Vietnamese'),
('VGB', 'VG', 'Virgin Islands (British)', 'British Virgin Island'),
('VIR', 'VI', 'Virgin Islands (U.S.)', 'U.S. Virgin Island'),
('WLF', 'WF', 'Wallis and Futuna', 'Wallis and Futuna, Wallisian or Futunan'),
('ESH', 'EH', 'Western Sahara', 'Sahrawi, Sahrawian, Sahraouian'),
('YEM', 'YE', 'Yemen', 'Yemeni'),
('ZMB', 'ZM', 'Zambia', 'Zambian'),
('ZWE', 'ZW', 'Zimbabwe', 'Zimbabwean');


--
-- UPDATE DATABASE VERSION
--

INSERT INTO database_updates (major_version, minor_version) VALUES (1, 6);
