--
-- FIX THE CODE FOR 'ANDORRA'
--

UPDATE countries SET code = 'AND' WHERE code = 'and';

--
-- UPDATE THE COUNTRY LIST TO INCLUDE ALL SARS COUNTRIES
--

INSERT INTO countries( name, alpha_2_code, code, is_passport, is_address) VALUES
('AFGHANISTAN','AF','AFG',true,true),
('ÅLAND ISLANDS','AX','ALA',true,true),
('ALBANIA','AL','ALB',true,true),
('ALGERIA','DZ','DZA',true,true),
('AMERICAN SAMOA','AS','ASM',true,true),
('ANDORRA','AD','AND',true,true),
('ANGOLA','AO','AGO',true,true),
('ANGUILLA','AI','AIA',true,true),
('ANTARCTICA','AQ','ATA',true,true),
('ANTIGUA AND BARBUDA','AG','ATG',true,true),
('ARGENTINA','AR','ARG',true,true),
('ARMENIA','AM','ARM',true,true),
('ARUBA','AW','ABW',true,true),
('AUSTRALIA','AU','AUS',true,true),
('AUSTRIA','AT','AUT',true,true),
('AZERBAIJAN','AZ','AZE',true,true),
('BAHAMAS','BS','BHS',true,true),
('BAHRAIN','BH','BHR',true,true),
('BANGLADESH','BD','BGD',true,true),
('BARBADOS','BB','BRB',true,true),
('BELARUS','BY','BLR',true,true),
('BELGIUM','BE','BEL',true,true),
('BELIZE','BZ','BLZ',true,true),
('BENIN','BJ','BEN',true,true),
('BERMUDA','BM','BMU',true,true),
('BHUTAN','BT','BTN',true,true),
('BOLIVIA (PLURINATIONAL STATE OF)','BO','BOL',true,true),
('BONAIRE, SINT EUSTATIUS AND SABA','BQ','BES',true,true),
('BOSNIA AND HERZEGOVINA','BA','BIH',true,true),
('BOTSWANA','BW','BWA',true,true),
('BOUVET ISLAND','BV','BVT',true,true),
('BRAZIL','BR','BRA',true,true),
('BRITISH INDIAN OCEAN TERRI.T.O.RY','IO','IOT',true,true),
('BRUNEI DARUSSALAM','BN','BRN',true,true),
('BULGARIA','BG','BGR',true,true),
('BURKINA FASO','BF','BFA',true,true),
('BURUNDI','BI','BDI',true,true),
('CAMBODIA','KH','KHM',true,true),
('CAMEROON','CM','CMR',true,true),
('CANADA','CA','CAN',true,true),
('CAPE VERDE','CV','CPV',true,true),
('CAYMAN ISLANDS','KY','CYM',true,true),
('CENTRAL AFRICAN REPUBLIC','CF','CAF',true,true),
('CHAD','TD','TCD',true,true),
('CHILE','CL','CHL',true,true),
('CHINA','CN','CHN',true,true),
('CHRISTMAS ISLAND','CX','CXR',true,true),
('COCOS (KEELING) ISLANDS','CC','CCK',true,true),
('COLOMBIA','CO','COL',true,true),
('COMOROS','KM','COM',true,true),
('CONGO','CG','COG',true,true),
('CONGO (THE DEMOCRATIC REPUBLIC OF THE)','CD','COD',true,true),
('COOK ISLANDS','CK','COK',true,true),
('COSTA RICA','CR','CRI',true,true),
('CÔTE D''IVOIRE','CI','CIV',true,true),
('CROATIA','HR','HRV',true,true),
('CUBA','CU','CUB',true,true),
('CURAÇAO','CW','CUW',true,true),
('CYPRUS','CY','CYP',true,true),
('CZECH REPUBLIC','CZ','CZE',true,true),
('DENMARK','DK','DNK',true,true),
('DJIBOUTI','DJ','DJI',true,true),
('DOMINICA','DM','DMA',true,true),
('DOMINICAN REPUBLIC','DO','DOM',true,true),
('ECUADOR','EC','ECU',true,true),
('EGYPT','EG','EGY',true,true),
('EL SALVADOR','SV','SLV',true,true),
('EQUATORIAL GUINEA','GQ','GNQ',true,true),
('ERITREA','ER','ERI',true,true),
('ESTONIA','EE','EST',true,true),
('ETHIOPIA','ET','ETH',true,true),
('FALKLAND ISLANDS (MALVINAS)','FK','FLK',true,true),
('FAROE ISLANDS','FO','FRO',true,true),
('FIJI','FJ','FJI',true,true),
('FINLAND','FI','FIN',true,true),
('FRANCE','FR','FRA',true,true),
('FRENCH GUIANA','GF','GUF',true,true),
('FRENCH POLYNESIA','PF','PYF',true,true),
('FRENCH SOUTHERN TERRI.T.O.RIES','TF','ATF',true,true),
('GABON','GA','GAB',true,true),
('GAMBIA','GM','GMB',true,true),
('GEORGIA','GE','GEO',true,true),
('GERMANY','DE','DEU',true,true),
('GHANA','GH','GHA',true,true),
('GIBRALTAR','GI','GIB',true,true),
('GREECE','GR','GRC',true,true),
('GREENLAND','GL','GRL',true,true),
('GRENADA','GD','GRD',true,true),
('GUADELOUPE','GP','GLP',true,true),
('GUAM','GU','GUM',true,true),
('GUATEMALA','GT','GTM',true,true),
('GUERNSEY','GG','GGY',true,true),
('GUINEA','GN','GIN',true,true),
('GUINEA-BISSAU','GW','GNB',true,true),
('GUYANA','GY','GUY',true,true),
('HAITI','HT','HTI',true,true),
('HEARD ISLAND AND MCDONALD ISLANDS','HM','HMD',true,true),
('HOLY SEE (VATICAN CITY STATE)','VA','VAT',true,true),
('HONDURAS','HN','HND',true,true),
('HONG KONG (SPECIAL ADMINISTRATIVE REGION OF CHINA)','HK','HKG',true,true),
('HUNGARY','HU','HUN',true,true),
('ICELAND','IS','ISL',true,true),
('INDIA','IN','IND',true,true),
('INDONESIA','ID','IDN',true,true),
('IRAN (ISLAMIC REPUBLIC OF)','IR','IRN',true,true),
('IRAQ','IQ','IRQ',true,true),
('IRELAND','IE','IRL',true,true),
('ISLE OF MAN','IM','IMN',true,true),
('ISRAEL','IL','ISR',true,true),
('ITALY','IT','ITA',true,true),
('JAMAICA','JM','JAM',true,true),
('JAPAN','JP','JPN',true,true),
('JERSEY','JE','JEY',true,true),
('JORDAN','JO','JOR',true,true),
('KAZAKHSTAN','KZ','KAZ',true,true),
('KENYA','KE','KEN',true,true),
('KIRIBATI','KI','KIR',true,true),
('KOREA (DEMOCRATIC PEOPLE''S REPUBLIC OF)','KP','PRK',true,true),
('KOREA (REPUBLIC OF)','KR','KOR',true,true),
('KUWAIT','KW','KWT',true,true),
('KYRGYZSTAN','KG','KGZ',true,true),
('LAO PEOPLE''S DEMOCRATIC REPUBLIC','LA','LAO',true,true),
('LATVIA','LV','LVA',true,true),
('LEBANON','LB','LBN',true,true),
('LESOTHO','LS','LSO',true,true),
('LIBERIA','LR','LBR',true,true),
('LIBYA','LY','LBY',true,true),
('LIECHTENSTEIN','LI','LIE',true,true),
('LITHUANIA','LT','LTU',true,true),
('LUXEMBOURG','LU','LUX',true,true),
('MACAO (SPECIAL ADMINISTRATIVE REGION OF CHINA)','MO','MAC',true,true),
('MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF)','MK','MKD',true,true),
('MADAGASCAR','MG','MDG',true,true),
('MALAWI','MW','MWI',true,true),
('MALAYSIA','MY','MYS',true,true),
('MALDIVES','MV','MDV',true,true),
('MALI','ML','MLI',true,true),
('MALTA','MT','MLT',true,true),
('MARSHALL ISLANDS','MH','MHL',true,true),
('MARTINIQUE','MQ','MTQ',true,true),
('MAURITANIA','MR','MRT',true,true),
('MAURITIUS','MU','MUS',true,true),
('MAYOTTE','YT','MYT',true,true),
('MEXICO','MX','MEX',true,true),
('MICRONESIA (FEDERATED STATES OF)','FM','FSM',true,true),
('MOLDOVA (REPUBLIC OF)','MD','MDA',true,true),
('MONACO','MC','MCO',true,true),
('MONGOLIA','MN','MNG',true,true),
('MONTENEGRO','ME','MNE',true,true),
('MONTSERRAT','MS','MSR',true,true),
('MOROCCO','MA','MAR',true,true),
('MOZAMBIQUE','MZ','MOZ',true,true),
('MYANMAR','MM','MMR',true,true),
('NAMIBIA','NA','NAM',true,true),
('NAURU','NR','NRU',true,true),
('NEPAL','NP','NPL',true,true),
('NETHERLANDS','NL','NLD',true,true),
('NEW CALEDONIA','NC','NCL',true,true),
('NEW ZEALAND','NZ','NZL',true,true),
('NICARAGUA','NI','NIC',true,true),
('NIGER','NE','NER',true,true),
('NIGERIA','NG','NGA',true,true),
('NIUE','NU','NIU',true,true),
('NORFOLK ISLAND','NF','NFK',true,true),
('NORTHERN MARIANA ISLANDS','MP','MNP',true,true),
('NORWAY','NO','NOR',true,true),
('OMAN','OM','OMN',true,true),
('PAKISTAN','PK','PAK',true,true),
('PALAU','PW','PLW',true,true),
('PALESTINE (STATE OF)','PS','PSE',true,true),
('PANAMA','PA','PAN',true,true),
('PAPUA NEW GUINEA','PG','PNG',true,true),
('PARAGUAY','PY','PRY',true,true),
('PERU','PE','PER',true,true),
('PHILIPPINES','PH','PHL',true,true),
('PITCAIRN','PN','PCN',true,true),
('POLAND','PL','POL',true,true),
('PORTUGAL','PT','PRT',true,true),
('PUERTO RICO','PR','PRI',true,true),
('QATAR','QA','QAT',true,true),
('RÉUNION','RE','REU',true,true),
('ROMANIA','RO','ROU',true,true),
('RUSSIAN FEDERATION','RU','RUS',true,true),
('RWANDA','RW','RWA',true,true),
('SAINT BARTHÉLEMY','BL','BLM',true,true),
('SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA','SH','SHN',true,true),
('SAINT KITTS AND NEVIS','KN','KNA',true,true),
('SAINT LUCIA','LC','LCA',true,true),
('SAINT MARTIN (FRENCH PART)','MF','MAF',true,true),
('SAINT PIERRE AND MIQUELON','PM','SPM',true,true),
('SAINT VINCENT AND THE GRENADINES','VC','VCT',true,true),
('SAMOA','WS','WSM',true,true),
('SAN MARINO','SM','SMR',true,true),
('SAO TOME AND PRINCIPE','ST','STP',true,true),
('SAUDI ARABIA','SA','SAU',true,true),
('SENEGAL','SN','SEN',true,true),
('SERBIA','RS','SRB',true,true),
('SEYCHELLES','SC','SYC',true,true),
('SIERRA LEONE','SL','SLE',true,true),
('SINGAPORE','SG','SGP',true,true),
('SINT MAARTEN (DUTCH PART)','SX','SXM',true,true),
('SLOVAKIA','SK','SVK',true,true),
('SLOVENIA','SI','SVN',true,true),
('SOLOMON ISLANDS','SB','SLB',true,true),
('SOMALIA','SO','SOM',true,true),
('SOUTH AFRICA','ZA','ZAF',true,true),
('SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','GS','SGS',true,true),
('SOUTH SUDAN','SS','SSD',true,true),
('SPAIN','ES','ESP',true,true),
('SRI LANKA','LK','LKA',true,true),
('SUDAN','SD','SDN',true,true),
('SURINAME','SR','SUR',true,true),
('SVALBARD AND JAN MAYEN','SJ','SJM',true,true),
('SWAZILAND','SZ','SWZ',true,true),
('SWEDEN','SE','SWE',true,true),
('SWITZERLAND','CH','CHE',true,true),
('SYRIAN ARAB REPUBLIC','SY','SYR',true,true),
('TAIWAN','TW','TWN',true,true),
('TAJIKISTAN','TJ','TJK',true,true),
('TANZANIA (UNITED REPUBLIC OF)','TZ','TZA',true,true),
('THAILAND','TH','THA',true,true),
('TIMOR-LESTE','TL','TLS',true,true),
('TOGO','TG','TGO',true,true),
('TOKELAU','TK','TKL',true,true),
('TONGA','TO','TON',true,true),
('TRINIDAD AND TOBAGO','TT','TTO',true,true),
('TUNISIA','TN','TUN',true,true),
('TURKEY','TR','TUR',true,true),
('TURKMENISTAN','TM','TKM',true,true),
('TURKS AND CAICOS ISLANDS','TC','TCA',true,true),
('TUVALU','TV','TUV',true,true),
('UGANDA','UG','UGA',true,true),
('UKRAINE','UA','UKR',true,true),
('UNITED ARAB EMIRATES','AE','ARE',true,true),
('UNITED KINGDOM','GB','GBR',true,true),
('UNITED KINGDOM (DEPENDENT TERRITORIES CITIZEN)','GB','GBD',true,false),
('UNITED KINGDOM (NATIONAL OVERSEES)','GB','GBN',true,false),
('UNITED KINGDOM (OVERSEAS CITIZEN)','GB','GBO',true,false),
('UNITED KINGDOM (PROTECTED PERSON)','GB','GBP',true,false),
('UNITED KINGDOM (SUBJECT)','GB','GBS',true,false),
('UNITED STATES','US','USA',true,true),
('UNITED STATES MINOR OUTLYING ISLANDS','UM','UMI',true,false),
('UNSPECIFIED','ZN','ZNC',true,false),
('URUGUAY','UY','URY',true,true),
('UZBEKISTAN','UZ','UZB',true,true),
('VANUATU','VU','VUT',true,true),
('VENEZUELA (BOLIVARIAN REPUBLIC OF)','VE','VEN',true,true),
('VIETNAM','VN','VNM',true,true),
('VIRGIN ISLANDS (BRITISH)','VG','VGB',true,true),
('VIRGIN ISLANDS (U.S.)','VI','VIR',true,true),
('WALLIS AND FUTUNA','WF','WLF',true,true),
('WESTERN SAHARA','EH','ESH',true,true),
('YEMEN','YE','YEM',true,true),
('ZAMBIA','ZM','ZMB',true,true),
('ZIMBABWE','ZW','ZWE',true,true) 
ON CONFLICT (code) 
DO NOTHING;

--
-- CHANGE THE CASE OF THE COUNTRY NAMES
--

UPDATE countries SET name = INITCAP( name );

--
-- UPDATE DATABASE VERSION
--

INSERT INTO database_updates (major_version, minor_version) VALUES (1, 22);